'use strict';

var expect = require('chai').expect;
var eventPerLocationLib = require('../../graphs/eventsPerLocation');
var locations = [
  "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  "The Prototyping Lab @ NDC 111 MIddle Road S188969",
  "Plug-In@Blk71",
  "ArtScience Museum",
  "Microsoft Singapore, 22nd Floor, One Marina Boulevard, NTUC Cebtre",
  "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  "Toa Payoh Public Library",
  "Singapore General Hospital, Outram Road, Singapore 169608",
  "Elite Building, 20 Aljunied Rd, #06-00, Singapore 389805",
  "The Office, 75A Pagoda Street Singapore 059234",
  "HackerspaceSG",
  "Fuji Xerox Singapore",
  "Red Dot Traffic Building",
  "HackerspaceSG",
  "Advanced Technology Enterprise Training Centre, 31 Kaki Bukit Road 3, #05-09 Techlink (Lobby B), Singapore 417818",
  "Advanced Technology Enterprise Training Centre, 31 Kaki Bukit Road 3, #05-09 Techlink (Lobby B), Singapore 417818",
  "LT15, AS6, National University of Singapore",
  "Advanced Technology Enterprise Training Centre, 31 Kaki Bukit Road 3, #05-09 Techlink (Lobby B), Singapore 417818",
  "NUS CFA Studios",
  "Hyper Island in Singapore, 991B Alexandra Road #03-08/11, Singapore 119970",
  "99.co",
  "Ice Cold Beer @ SMU, 50 Stamford Road, Singapore",
  "Plug-In@Blk71",
  "Nitrous.IO, 1 Trengganu St, 2nd Floor, Singapore 058455",
  "Plug-in@Blk71, 71 Ayer Rajah Crescent, Singapore",
  "Hood Bar and Cafe @ Bugis+ (formerly Iluma), Bugis+, 201 Victoria Street, #05-07, Singapore 188067 ",
  "Shaw Foundation Alumni House Auditorium, Level 2, 11 Kent Ridge Drive, Singapore 119244",
  "Seminar Room 10, COM1 Building #02-10, 13 Computing Drive, NUS, Singapore 117417",
  "Urban Redevelopment Authority, The URA Centre Atrium, 45 Maxwell Road, Singapore 069118",
  "LT 15, AS6, National University of Singapore",
  "HackerspaceSG",
  "Chin Mee Chin Confectionery, 204 East Coast Road, Singapore 428903",
  "IDA Labs @ National Design Centre, 111 Middle Rd, #03-04, Singapore 188969",
  "IDA Labs @ National Design Centre, 111 Middle Rd, #03-04, Singapore 188969",
  "Plugin-In@BLK 71 Managed by NUS Enterprise, 71 Ayer Rajah Crescent, #02-18, Singapore 139951",
  "SMU School of Economics and Social Science, Seminar Room 5.2 (lift access only), Singapore Management University",
  "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  "Google Singapore, 8 Marina View, Asia Square Tower 1 Level 29",
  "The Working Capitol, 1 Keong Saik road, Singapore 089109",
  "*SCAPE The Colony, #04-01, 2 Orchard Link, Singapore 237978",
  "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  "The Office, 75A Pagoda Street Singapore 059234",
  "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  "ArtScience Museum",
  "Plug-In@Blk71",
  "Urban Redevelopment Authority, The URA Centre, 45 Maxwell Road, Singapore 069118",
  "The URA Centre, Atrium, 45 Maxwell Road, Singapore 069118",
  "NUS Hackerspace",
  "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  "Hackerspace, 344B King George's Avenue, Singapore",
  "Revolution Analytics Singapore Office, 51 Changi Business Park Central 2 #04-09/10",
  "Oo La Laa Cafe and Bistro, 2 Marne Rd, Singapore 208393",
  "Oo La Laa Cafe and Bistro, 2 Marne Rd, Singapore 208393",
  "237 South Bridge Rd, 237 S Bridge Rd, Singapore 058786",
  "Microsoft Singapore, 1 Marina Boulevard, Level 22, Singapore City 018989",
  "237 South Bridge Rd, 237 S Bridge Rd, Singapore 058786",
  "Stratasys, 988 Toa Payoh North, #07-06, Singapore 319002",
  // "401 Commonwealth Drive, Haw Par Technocentre, #07-01, Singapore",
  // "Stratasys, 988 Toa Payoh North, #07-06, Singapore 319002",
  // "Allied Solutions (S) Pte Ltd, 23 New Industrial Rd, #07-06/07 Solstice Business Center, Singapore 536209",
  // "The URA Centre, Atrium, 45 Maxwell Road, Singapore 069118",
  // "SR3, Town Plaza, UTown",
  // "237 South Bridge Rd, 237 S Bridge Rd, Singapore 058786",
  // "NTU Open Source Society",
  // "The URA Centre, Atrium, 45 Maxwell Road, Singapore 069118",
  // "237 South Bridge Rd, 237 S Bridge Rd, Singapore 058786",
  // "ArtScience Museum",
  // "Park NE of Marina Mall, Marina Mall / Marina Boulevard, Singapore",
  // "Q & M DENTAL Centre, City Square Mall, 180 Kitchener Road #b1-13/14, Singapore  208539",
  // "Q & M DENTAL Centre, City Square Mall, 180 Kitchener Road #b1-13/14, Singapore  208539",
  // "ArtScience Museum",
  // "Lifelong Learning Institute Singapore, 11 Eunos Road 8 #07-02,  408601",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Toa Payoh Public Library, Programme Zone, 6 Toa Payoh Central, Singapore 319191",
  // "O'Coffee Club (Harbourfront Centre), 1 Maritime square #01-65/66, Singapore",
  // "Toa Payoh Public Library, Programme Zone, 6 Toa Payoh Central, Singapore 319191",
  // "Advanced Technology Enterprise Training Centre, 31 Kaki Bukit Road 3, #05-09 Techlink (Lobby B), Singapore 417818",
  // "Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore 139951",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "Hood Bar and Cafe @ Bugis+ (formerly Iluma), Bugis+, 201 Victoria Street, #05-07, Singapore 188067 ",
  // "National Design Centre",
  // "HackerspaceSG",
  // "Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore 139951",
  // "ArtScience Museum",
  // "PayPal office in Millenia Tower, 1 Temasek Avenue Millenia Tower #14-01, Singapore",
  // "ThoughtWorks Pte. Ltd.,  87B Amoy Street, Level 3, Singapore 069906",
  // "Plug-In@Blk71",
  // "TR+37",
  // "SR3, Town Plaza, UTown",
  // "HackerspaceSG",
  // "Address will posted and emailed , prior to the meet.,, Singapore",
  // "Science Centre Singapore, Curie and Herschel Labs",
  // "Creamier Handcrafted Ice Cream and Coffee, Blk128, Toa Payoh Lorong 1, #01-835, Singapore 310128",
  // "PocketMath",
  // "HackerspaceSG",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "PayPal Singapore, Millenia Tower, 1 Temasek Avenue, Level 14, Singapore 039192",
  // "PayrollHero , 6th Floor, Ocean Financial Centre, 10 Collyer Quay, Singapore",
  // "Thoughtworks, 87B Amoy Street #04, Singapore 069906, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "PayPal Singapore Millenia Office",
  // "Sarnies, 136 Telok Ayer , Singapore",
  // "Hackerspace, 344B King George's Building, Singapore",
  // "The Learning Centre@Waterloo, Blk 261, Waterloo Street, #02-27A Waterloo Centre, Singapore 180261",
  // "IBM Singapore, TEC room, Level 1, 9 Changi Business Park Central 1, The IBM Place, Singapore 486048",
  // "Plug-In@Blk71",
  // "TR+37",
  // "JFDI Asia, 71 Ayer Rajah Crescent, #05-16, Singapore",
  // "Ya Kun Kaya Toast, 18 China St, #01-01, Singapore 049560",
  // "Odd-e Singapore - Goodland Building, 18 Roberts Lane, #05-01",
  // "SMU School of Economics and Social Science, Seminar Room 5.2 (lift access only), 90 Stamford Road, Singapore",
  // "Toa Payoh Hdb Hub",
  // "National Design Centre, Level 2",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "PayPal Singapore, Millenia Tower, 1 Temasek Avenue, Level 14, Singapore 039192, Singapore",
  // "Big Data for Social Good Challenge, Web only, Singapore",
  // "IDA Labs @ NDC National Design Centre , 111 Middle Road, #03-04 Singapore 188969 ",
  // "Microsoft Singapore, 22nd Floor, One Marina Boulevard, NTUC Cebtre",
  // "Millenia Tower",
  // "SR3, Town Plaza, UTown",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "WebEx, http://www.knowbigdata.com/page/big-data-hadoop-online-instructor-led-training-session-1-introduction-free, Singapore",
  // " 1.276109°N, 103.863727°E, Marina Mall, Singapore",
  // "TMC Academy, Lecture Theatre, , 250 Middle Rd, Singapore 188983",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "PayPal office in Millenia Tower, 1 Temasek Avenue Millenia Tower #14-01, Singapore",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Toa Payoh Public Library, Programme Zone, , 6 Toa Payoh Central, Singapore 319191",
  // "Science Centre Singapore",
  // "ArtScience Museum",
  // "Starbucks @ Plaza Singapura, 68 Orchard Road #01-53 Plaza Singapura Singapore 238839",
  // "Skyscanner, 39 Robinson Road, #09-01 Robinson Point, Singapore 068911",
  // "Science Centre Singapore",
  // "HackerspaceSG",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "Amoy Street Food Centre, Singapore",
  // "Red Hat, 8 Shenton Way, 10-01 AXA Tower, 068811 Singapore",
  // "OneMakerGroup at National Design, Centre 111 Middle Road #01-02, 188969, Singapore",
  // "Wheelock Place, 501 Orchard Road, Singapore",
  // "IDA Labs Level 2 @ National Design Centre, 111 Middle Road, #02-04, Singapore",
  // "Fuji Xerox Singapore Level 4",
  // "Tong Eng Building #11-11, 101 Cecil Street, #11-11 Tong Eng Building, Singapore 069533",
  // "Microsoft Singpaore, One Marina Boulevard, Level 21 Auditorum, Singapore 018989",
  // "Blu Jaz Cafe, 11 Bali Lane , Nearest MRT : Bugis, Singapore",
  // "National Design Centre, Level 2",
  // "Biopolis, , Matrix Auditorium, Level 2, 30 Biopolis Street, Singapore null",
  // "Matrix, Biopolis, 30 Biopolis Street, Singapore 138671",
  // "TR+37",
  // "Labrador Park MRT (CC27) Station Control, Labrador Park, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "NUS Plug-In@Blk71, Ayer Rajah Crescent, #05-16, Singapore",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "Toa Payoh Hdb Hub",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "Silicon Straits, 71 Ayer Rajah Crescent,  #06-11/12, Singapore 139951",
  // "Plug-In@Blk71",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "Science Centre Singapore Digital Design Centre",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "Singapore Botanic Gardens, Botanic Gardens MRT",
  // "Chinatown MRT Exit A, Chinatown MRT, Singapore",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "NUS Plug-In@Blk71, Ayer Rajah Crescent, #05-16, Singapore",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "237 South Bridge Road, 237 South Bridge Road, Singapore",
  // "NUS Plug-In@Blk71, 71 Ayer Rajah Crescent, #02-18, Singapore",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "237 (http://237.io/), 237 South Bridge Road Singapore 058786",
  // "Science Centre Singapore",
  // "Migme Hq",
  // ", , 237 South Bridge Road, Singapore 058786",
  // "PayPal Singapore, Millenia Tower, 1 Temasek Avenue, Level 14, Singapore 039192",
  // ", , 237 South Bridge Rd, Singapore 058786",
  // "TCC @ CQ Central, 6 Eu Tong Sen Street, 059817, Singapore",
  // "HackerspaceSG",
  // "Hood Bar and Cafe @ Bugis+ (formerly Iluma), Bugis+, 201 Victoria Street, #05-07, Singapore 188067 ",
  // "401 Commonwealth Drive, Haw Par Technocentre, #07-01, Singapore",
  // "IDA Labs Level 3 @ National Design Centre, 111 Middle Road, #03-04, 188969, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Neo, 53A Craig Road, Singapore",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "ThoughtWorks Pte. Ltd. 87B Amoy Street, Level 3 Singapore 069906",
  // "Nanyang Technological University, Singapore",
  // "SR3, Town Plaza, UTown",
  // "Toa Payoh Hdb Hub",
  // "Show Map OneMaker Group - OMG National Design Centre, 111 Middle Road, #01 - 02, Singapore",
  // "Hong Lim Complex, 531 Upper Cross Street #03-11, Singapore",
  // "Rakuten Asia Pte Ltd, 1 George Street, #16-02, Singapore",
  // "PayPal Singapore, Millenia Tower, 1 Temasek Avenue, Level 14, Singapore 039192",
  // "Center for Life Sciences (CeLS), Level 1, Seminar Room 2, , National University of Singapore, 28 Medical Drive, Singapore City 117456",
  // "Temasek Polytechnic Auditorium 2 & Foyer, , 21 Tampines Avenue 1, Singapore 529757",
  // "Temasek Polytechnic Auditorium 2 & Foyer, , 21 Tampines Avenue 1, Singapore 529757",
  // "Biopolis, Neuros Building, , Institute of Medical Biology, Level 6, Seminar Room 6.49 / 6.50, Singapore  138648",
  // "PayPal Singapore Millenia Office",
  // "Science Centre Singapore, , 15 Science Centre Rd, Singapore 609081",
  // "PayPal Singapore, Millenia Tower, 1 Temasek Avenue, Level 14, Singapore 039192",
  // "HackerspaceSG",
  // "Nanyang Technological University, School of Biological Sciences, , 60 Nanyang Drive, SBS-01n-22, Classroom 2, Singapore 637551",
  // "National University of Singapore, , Mechanobiology Institute, T-Lab Building Level 5 Meeting Room, Singapore 117411",
  // "Temasek Life Sciences Laboratory, , 1 Research Link National University of Singapore, Seminar room 01-17, Singapore 117604",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "ArtScience Museum",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "SR3, Town Plaza, UTown",
  // "TR+37",
  // "Home-Fix Singapore, XPC 2nd Floor, 19 Tai Seng Avenue, Home-Fix Building, #06-01, Singapore 534054",
  // "2 Kallang Avenue CT Hub, , #09-27, Singapore 339407",
  // "237 (http://237.io/), 237 South Bridge Road Singapore 058786",
  // "Unit 11 Lor 24A Geylang Singapore 398535",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Science Centre Singapore",
  // "Odd-e Singapore - Goodland Building, 18 Roberts Lane, #05-01",
  // "Qiushi Li, , Test, #02-77, blk177, clementi street 13, Singapore 120117",
  // "CLIFTONS SINGAPORE Level 11, Finexis Building 108 Robinson Road Singapore",
  // "The Plaza in National Library, , 100 Victoria St, Singapore 188064",
  // "#02-04, 111 Middle Road, National Design Centre, Singapore",
  // "PayPal Singapore Millenia Office",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "ArtScience Museum",
  // "SR3, Town Plaza (Level 2), University Town, NUS",
  // "HackerspaceSG",
  // "School of Information System, SMU, SIS Seminar Room 2-4, Level 2,School of Information System, SMU, 80 Stamford Road, Singapore",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "TMC Academy, Lecturer Theatre, , 250 Middle Rd, Singapore 188983",
  // "AWS Offices Singapore, 23 Church Street, Capital Square, #10-01, Singapore - 049481, +65-67220300",
  // "JFDI Asia, 71 Ayer Rajah Crescent, #05-16, Singapore",
  // "Sarnies, 136 Telok Ayer , Singapore",
  // "Paypal, #14-01, 1 Temasek Boulevard, Singapore 039192",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "PayPal office in Millenia Tower, 1 Temasek Avenue Millenia Tower #14-01, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "ArtScience Museum",
  // "Plug-In@Blk71",
  // "M2 Academy, 1 Orchard Road Singapore, 238824",
  // "TR+37",
  // "SR3, Town Plaza, UTown",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "Bukit Batok Community Club, Lvl 4 YEC Lounge Room #04-01, , 21 Bukit Batok Central, Singapore 659959",
  // "My Awesome Cafe, 202 Telok Ayer Street, Singapore 068639",
  // "Mountbatten Square, , 229 Mountbatten Rd, Singapore 398007",
  // "Viki, Block 59 Mohamed Sultan Road #04-08/09/10, Singapore 238999",
  // "Margaret Drive Park by Queensway, Margaret Close, Singapore",
  // "Hackerspace, 344B King George's Building, Singapore",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "IDA Labs @ National Design Centre, , 111 Middle Rd, #03-04, Singapore 188969",
  // "Zopim, , 401 Commonwealth Drive, Haw Par Technocentre, #07-01, 149598, Singapore null",
  // "The Growell Pop Up, 107/109 Rowell Road, Singapore",
  // "HackerspaceSG",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Toa Payoh Public Library",
  // "Thought Works,  Level 3, 87B Amoy Street, 069906, Singapore",
  // "Viki Pte Ltd , Block 59, Mohamed Sultan Road, #04-08 Singapore 238999.",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // ", , Killiney Rd, Singapore null",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Plug-In@Blk71",
  // "The Penny Black,  26/27 Boat Quay, Singapore 049817.",
  // "SR3, Town Plaza, UTown",
  // "The Penny Black,  26/27 Boat Quay, Singapore 049817.",
  // "Real Food Cafe, 110 Killiney Road S(239549), Singapore",
  // "SMU School of Business, Seminar Room 2-2, 50 Stamford Road, Singapore 178899",
  // "Smartkarma",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "PayPal Singapore, Millenia Tower, 1 Temasek Avenue, Level 14, Singapore 039192",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "TCC @ CQ Central, 6 Eu Tong Sen Street, 059817, Singapore",
  // "Sea Asia Exhibition, , Sands Exhibit Hall, Level 3 - Rooms 3111-3112, Singapore null",
  // "Computing 1, 13 Computing Drive, , School of Computing, National University of Singapore, Singapore 117417",
  // "Hood Bar and Cafe @ Bugis+ (formerly Iluma), Bugis+, 201 Victoria Street, #05-07, Singapore 188067 ",
  // "PayPal, #14-01, Millenia Tower, 1 Temasek Avenue, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "#02-04, 111 Middle Road, National Design Centre, Singapore",
  // "IDA Lab @ National Design Center , #03-04 111 Middle Road, Singapore",
  // "Lifelong Learning Institute, , 11 EUNOS ROAD 8, Singapore 408601",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "Hackerspace.SG, 344B King George’s Avenue, Singapore 208576",
  // "Hong Lim Complex, 531 Upper Cross Street #03-11, Singapore",
  // "川味人家 (Chuan Wei Ren Jia), 17 Mosque Street Singapore 059497 6220 5766",
  // "Fuji Xerox Singapore, 80 Anson Road, Fuji Xerox Towers, S(079907)",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Singapore Polytechnic - The Auditorium, , 500 Dover Road, Singapore 139651",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "Paypal, #14-01, 1 Temasek Boulevard, Singapore 039192",
  // "IDA Labs Level 2 @ National Design Centre, 111 Middle Road, #02-04, Singapore 188969",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Lowercase, 1 McNally St, Blk D #01-01, Singapore",
  // "Red Dot Ventures Incubation Office, , Block 79 Ayer Rajar Crescent, #04 - 03-04, Singapore 579723",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "PayPal office in Millenia Tower, 1 Temasek Avenue Millenia Tower #14-01, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "HackerspaceSG",
  // "AWS Offices Singapore, 23 Church Street, Capital Square, #10-01, Singapore - 049481, +65-67220300",
  // "Lowercase, 1 McNally St, Blk D #01-01, Singapore",
  // "Amazon Web Services Office, Level 10, 23 Church Street, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "Fusionopolis, , Room Singapore Symbiosis 10936  Level 9, Autodesk Asia Pte Ltd, 3 Fusionopolis Way, #10-21 Symbiosis, 138633, Singapore 138633",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "ArtScience Museum",
  // "AWS Offices Singapore, 23 Church Street, Capital Square #10-01, 049481 Singapore",
  // "ArtScience Museum",
  // "Plug-In@Blk71",
  // "Science Centre Singapore",
  // "237 (http://237.io/), 237 South Bridge Road Singapore 058786",
  // "Sonoport, Block 71 Ayer Rajah Crescent, #04-18, Singapore",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Toa Payoh Library, 6 Toa Payoh Central, Singapore",
  // "Lowercase, 1 McNally St, Blk D #01-01, Singapore",
  // "237 South Bridge Rd, , 237 S Bridge Rd, Singapore 058786",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "PayPal Singapore, Suntec Tower 5",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "237 (http://237.io/), 237 South Bridge Road Singapore 058786",
  // "Microsoft Singpaore, One Marina Boulevard, Level 21 Auditorum, Singapore 018989",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Ocean Financial Center, , 10 Collyer Quay, #06-07 (BGC Office), Singapore 049315",
  // "Fuji Xerox Singapore, 80 Anson Road, Fuji Xerox Towers, S(079907)",
  // "Fuji Xerox Singapore",
  // "237 South Bridge Rd, , 237 S Bridge Rd, Singapore 058786",
  // "The Co-foundry, Unit 11 Lor 24A Geylang Singapore 398535",
  // "The Working Capitol, 1 Keong Saik Road, Singapore 089109",
  // "International Plaza, , 10 Anson Road, #36-05A, SINGAPORE 079903",
  // "Plug-In@Blk71",
  // "LT9, ,  NS4-04-39, Nanyang Technological University, Singapore 639798",
  // "237 South Bridge Rd, , 237 S Bridge Rd, Singapore 058786",
  // "PayPal Singapore, Suntec Tower 5",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "HackerspaceSG",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Thought Works,  Level 3, 87B Amoy Street, 069906, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Lowercase, 1 McNally St, Blk D #01-01, Singapore",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Autodesk Asia Pte Ltd",
  // "IDA Labs @ NDC National Design Centre , 111 Middle Road, #03-04 Singapore 188969 ",
  // "The Co-Foundry, Unit 11 Lor 24A Geylang Singapore 398535 ",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "#Selfie Coffee Singapore, 11 Haji Lane, 189204 Singapore",
  // "IO, , 7000 Ang Mo Kio Avenue 5, Singapore null",
  // "Nonstop Games @ King Studio 12 Kallang Ave #03-20 Aperia Singapore 339511",
  // "Science Centre Singapore",
  // "Science Centre Singapore",
  // "ArtScience Museum",
  // "Parkroyal on Kitchener Road, 181 Kitchener Road, Singapore 208533",
  // "Viki, , Block 59 Mohamed Sultan Road, #04-08/09/10, Singapore null",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Lowercase, 1 McNally St, Blk D #01-01, Singapore",
  // "HP Invent Centre, , 450 Alexandra Rd, Singapore 119960",
  // "Offices of RHT Taylor-Wessing, Six Battery Road, #10-01, 049909, Singapore",
  // "Singapore Management University, School of Economics, Level 2, Seminar Room 2.5, 90 Stamford Road, Singapore Management University, Singapore 178903",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // " #03-04, IDA labs @ National Design Centre,  #03-04, 111 Middle Road, 188969, Singapore",
  // "Plug-In@Blk71",
  // "Singapore Management University, School of Economics, Level 4, Seminar Room 4.3, 90 Stamford Road, Singapore Management University, 178903",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "Rhu Cross, Rhu Cross, Singapore",
  // "Level 33, 8 Marina Blvd 33-01 Marina Bay Financial Tower, Singapore",
  // "Lifelong Learning Institute, , 11 EUNOS ROAD 8, Singapore 408601",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "IDA Labs Level 2 @ National Design Centre, 111 Middle Road, #02-04, Singapore 188969",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Nitrous.IO, 1 Trengganu St, 2nd Floor, Singapore 058455",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "ArtScience Museum",
  // "452 North Bridge Rd, , Chan Brothers Building, #04-00, (Near Bugis Junction), Singapore 188733",
  // "HIKVISION SINGAPORE PTE LTD OFFICE, , 18 Sin Ming Ln,#08-07, MIDVIEW CITY, Singapore 573960",
  // "Science Centre Singapore",
  // "Plug-In@Blk71",
  // "Science Centre Singapore",
  // "261, Waterloo Street,#04-35, Waterloo Centre, Singapore 180261, 261, Waterloo Street,#04-35, Waterloo Centre, Singapore 180261",
  // "IDA Labs Level 3 @ National Design Centre, 111 Middle Road, #03-04, 188969, Singapore",
  // "ArtScience Museum",
  // "IDA Labs @ National Design Centre, 111 Middle Road, #03-04, Singapore",
  // "Lau Pa Sat, 18 Raffles Quay, Lau Pa Sat Festival Market,  048582 , Singapore",
  // "Home-Fix XPC",
  // "PayPal Singapore, 5 Temasek Boulevard, Level 9, Suntec Tower 5, Singapore 038985",
  // "IDA Labs @ National Design Centre, 111 Middle Road, Nation Design Centre, IDA Labs @ 03-04, Singapore 188969",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "Toa Payoh Public Library",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "PayPal, Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985, Singapore",
  // "Kapok Cafe, #01-05 National Design Centre, 111 Middle Road, Singapore",
  // "JFDI.ASIA @ Blk 71, , 71 Ayer Rajah Crescent #05-16, SINGAPORE 139951",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "SMU, School of Info Systems, Room 3-3, 80 Stamford Road , Singapore",
  // "Hackerspace, 344B King George's Building, Singapore",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "HIKVISION SINGAPORE PTE LTD OFFICE, , 18 Sin Ming Ln,#08-07, MIDVIEW CITY, Singapore 573960",
  // "Stephen Riady Centre",
  // "The Hive, Blk K, , ITE College Central (Ang Mo Kio), 2 Ang Mo Kio Drive, Singapore 567720",
  // "Science Centre Singapore",
  // "ArtScience Museum",
  // "The Co-Foundry",
  // "Block 71 Ayer Rajah Crescent, #06-26, Singapore 139951",
  // "HackerspaceSG",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Launchpad@One-North, , Block 79 Ayer Rajah Crescent, #04-03/04, Singapore 139955",
  // "NSHC PTE Ltd, 8 Shenton Way AXA Tower, #04-01, Singapore 068811",
  // "SMU School of Economics, Seminar Room 2.6, 90 Stamford Road, 178903, Singapore",
  // "SmartSpace, 261 Waterloo Street, #03-32, Singapore 180261",
  // "GrabTaxi R&D Center, 138 Cecil Street, Cecil Court Singapore 069538",
  // "GrabTaxi R&D Centre, 138 Cecil Street, Cecil Court Singapore 069538",
  // "PayPal Singapore, Suntec Tower 5, 5 Temasek Boulevard #09-01 ",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "BASH, , Blk 79 Ayer Rajah Crescent #03-01, Singapore 139955",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "HIKVISION SINGAPORE PTE LTD OFFICE, , 18 Sin Ming Ln,#08-07, MIDVIEW CITY, Singapore 573960",
  // "Launchpad@One-North, , Block 79 Ayer Rajah Crescent, #04-03/04, Singapore 139955",
  // "Blk K, Level 4 Room K407, , ITE College Central, 2 Ang Mo Kio Drive, Singapore 567720",
  // "ArtScience Museum",
  // "SMU School of Economics and Social Science, Seminar Room 5.2 (lift access only), 90 Stamford Road, Singapore",
  // "Blk K, Level 4 Room K407, , ITE College Central, 2 Ang Mo Kio Drive, Singapore 567720",
  // "Blk K, Level 4 Room K407, , ITE College Central, 2 Ang Mo Kio Drive, Singapore 567720",
  // "The Hive, Blk K, Level 4 Room K407, , ITE College Central, 2 Ang Mo Kio Drive, Singapore 567720",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Genexis Theatre, , Fusionopolis, 1 Fusionopolis Way, Fusionopolis (Connexis Tower), Singapore 138632",
  // "PayPal Singapore, 5 Temasek Boulevard, Suntec Tower 5, Level 7, #07-01",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Neo Innovation , 53A Craig Road , 089691, Singapore",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "BASH, 79 Ayer Rajah Crescent #03, Singapore",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Plug-In@Blk71",
  // "FIV五 @ Great Eastern Centre, 1 Pickering Street 048659, Singapore",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "TCC, POMO, 1 Selegie Road #01-02 & #02-25 PoMo, 188306, Singapore",
  // "HackerspaceSG",
  // "Amazon Web Services Office, Level 10, 23 Church Street, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Thoughtworks, 87B Amoy Street #04, Singapore 069906, Singapore",
  // "Neo Office, 53A Craig Road, Singapore",
  // "IBM Client Centre, No.6 Tampines Industrial Ave 5 ,Singaore 528760, Singapore",
  // "TradeGecko Office, 101c Telok Ayer, 068574, Singapore",
  // "SMU School of Economics, Seminar Room 2.6, 90 Stamford Road, 178903, Singapore",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Hackerspace.SG, 344B King George's Avenue, Singapore",
  // "Plug-In@Blk71",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Marina Bay Financial Centre Tower 2, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, 018983, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Huge Singapore, 33 Ann Siang Rd, Suite 31A",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Paypal at Suntec , 5 Temasek Blvd, #07-01 Suntec Tower Five, Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "ArtScience Museum",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Plug-In@Blk71",
  // "15, Tampines street 11",
  // "Singapore Management University, Lee Kong Chian School of Business, Seminar Room 2.4, 50 Stamford Road",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "AWS Offices Singapore, 23 Church Street, Capital Square, #10-01, Singapore - 049481, +65-67220300",
  // "Toa Payoh Public Library",
  // "NTUC Auditorium, One Marina Boulevard, No 1, Marina Boulevard, Singapore",
  // "IDA Labs Level 2 @ National Design Centre, 111 Middle Road, #02-04, Singapore",
  // "Fuji Xerox Singapore, 80 Anson Road, Fuji Xerox Towers, S(079907)",
  // "TradeGecko Office, 121 Telok Ayer, Singapore",
  // "The Daily Roundup",
  // "Oberstrasse, 809 French Rd, Singapore 200809",
  // "Skyscanner Singapore",
  // "HackerspaceSG",
  // "Cook & Brew Gastrobar, The Westin Singapore, 12 Marina View, Asia Square Tower 2, Level 33",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "National Design Centre, 111 Middle Road National Design Centre #01-02 Singapore",
  // "SkyScanner Ltd, 39 Robinson Road #09-01 Robinson Point, Singapore",
  // "The Co 75 High Street Singapore 179435, 75 High Street Singapore 179435",
  // "iDA Labs @National Design Centre, 111 Middle Road, #03-04, Singapore 188969",
  // "TradeGecko Office, 121 Telok Ayer, Singapore",
  // "Conference room “Blubox II” (20th floor), Hong Leon Building, 16 Raffles Quay, near Lau Pa Sat, Singapore",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "PayPal Singapore, 5 Temasek Boulevard, Level 9, Suntec Tower 5, Singapore 038985",
  // "Datwyler, 30 Toh Guan Road #01-01A (Opp IMM, near Furniture Mall).  , Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "IDA Labs Level 2 @ National Design Centre, 111 Middle Road, #02-04, Singapore",
  // "Institute for Infocomm Research (I²R), 1 Fusionopolis Way 138632, Singapore",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "ArtScience Museum",
  // "Park Mall Singapore #11-13, 9 Penang Road, Park Mall Singapore 238459 #11-13 ",
  // "1925, 2nd Floor, 369 Jalan Besar Singapore 208997, Singapore",
  // "PayPal, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985, Singapore",
  // "The Substation, 45 Armenian Street, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "SmartSpace, 261 Waterloo Street, #03-32, Singapore 180261",
  // "Thoughtworks, 87B Amoy Street #04, Singapore 069906, Singapore",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "PayPal office at 5 Temasek Boulevard, Level 7, Suntec Tower 5, Singapore 038985",
  // "TradeGecko Office, 121 Telok Ayer, Singapore",
  // "Microsoft Singpaore, One Marina Boulevard, Level 21 Auditorum, Singapore 018989",
  // "Red Hat, 8 Shenton Way, 10-01 AXA Tower, 068811 Singapore",
  // "Alumni Medical Centre, No.2 College Road, Singapore 169850",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Plug-In@Blk71",
  // "川味人家 (Chuan Wei Ren Jia), 17 Mosque Street Singapore 059497 6220 5766",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "Margaret Drive Park by Queensway, Margaret Close, Singapore",
  // "LT4, Block T4A, Level 1, Singapore Polytechnic, 500 Dover Road",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Datwyler, 30 Toh Guan Road #01-01A (Opp IMM, near Furniture Mall).  , Singapore",
  // "SkyScanner Ltd, 39 Robinson Road #09-01 Robinson Point, Singapore",
  // "Drury Lane Cafe,  94 Tanjong Pagar Rd, Singapore",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "Pasir Ris Beach Park",
  // "Toa Payoh Public Library",
  // "Omni Theatre",
  // "PayPal office at 5 Temasek Boulevard, Level 7, Suntec Tower 5, Singapore 038985",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Everything with Fries (Orchard Central), 181 Orchard Road, #01-24/25, Singapore",
  // "Plugin@Blk71, 71 Ayer Rajah Crescent,  #02-18, Singapore 139951",
  // "Thought Works,  Level 3, 87B Amoy Street, 069906, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "Xin Wang Hong Kong Cafe, Plaza Singapura, #06-08/09/10, Singapore",
  // "22CF12, Level 22, Microsoft Singapore, Singapore 018989, One Marina Boulevard",
  // "Microsoft Singapore",
  // "Wego, 100 Beach Road #23-07/13 Shaw Tower Singapore 189702",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "SmartSpace, 261 Waterloo Street, #03-32, Singapore 180261",
  // "PayPal Singapore, Suntec Tower 5, 5 Temasek Boulevard #09-01 ",
  // "Neo Office, 53A Craig Road, Singapore",
  // "PropertyGuru, 51 Goldhill Plaza #11-03 (circular building next to United Square), Singapore",
  // "NUS Runme Shaw CFA Studios, Activity Room",
  // "344B King George's Rd, 208576",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "#03-04, IDA Labs@NDC 111 Middle Road, National Design Centre, Singapore 188969., IDA Labs@NDC 111 Middle Road, National Design Centre",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "ArtScience Museum",
  // "Prototyping Lab @ NDC, 111 Middle Road, National Design Centre, #01-02 Singapore",
  // "Seminar Room 1, School of Computing, National University of Singapore",
  // "SiS Building, 4 Leng Kee Road #03-03, Singapore",
  // "NTU Open Source Society",
  // "Armenian Street",
  // "ArtScience Museum",
  // "Hackerspace, 344B King George's Avenue, Singapore",
  // "ArtScience Museum",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Amazon Web Services Office, Level 10, 23 Church Street, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Sandcrawler, 1 Fusionopolis View #08-01 S138577, Singapore",
  // "Neo Innovation , 53A Craig Road , 089691, Singapore",
  // " #03-04, IDA labs @ National Design Centre,  #03-04, 111 Middle Road, 188969, Singapore",
  // "MakerAsia",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "PayPal Singapore, Suntec City, 5 Temasek Blvd, #07-01 Suntec Tower Five, 038985",
  // "Auston Institute, 50 Ophir Road, Level 3, Room 3-5, Singapore",
  // "Amazon Web Services Singapore, #10-01, 23 Church Street, Singapore 049481",
  // "Medical Alumni Association",
  // "Seminar Room 2, School of Computing, 13 Computing Drive",
  // "The Nest Theatre @ Innovation Centre",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "Google, 8 Marina View, Level 32, Asia Square 1, 018960 (downtown Mrt)",
  // "SkyScanner Ltd, 39 Robinson Road #09-01 Robinson Point, Singapore",
  // "Yahava KoffeeWorks (Singapore), 4 Jalan Gelenggang, Singapore 578188",
  // "HackerspaceSG",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "PayPal Singapore, Suntec City, 5 Temasek Blvd, #07-01 Suntec Tower Five, 038985",
  // "Thoughtworks, 87B Amoy Street #04, Singapore 069906, Singapore",
  // "The Exchange, Marina View, Asia Square Tower 1, Singapore 018960",
  // "Starbucks @ Biopolis, 70 Biopolis Street, #01-03, Singapore 138547",
  // "TradeGecko Office, 121 Telok Ayer, Singapore",
  // "Auston Institute, 50 Ophir Road, Level 3, Room 3-5, Singapore",
  // "SR3, Town Plaza, UTown",
  // "NTU Open Source Society",
  // "SiS Building, 4 Leng Kee Road #03-03, Singapore",
  // "大衆酒場, 100 am shopping mall 1F, 100 Tras Street, Singapore, 079027",
  // "Auston Institute of Management, 50 Ophir Road, #02-00, Singapore",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Toa Payoh Public Library",
  // "Netsuite, 9 Battery Road, #08-01, Straits Trading Building, Singapore",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "Suntec City Convention Centre, Hall 403, 1 Raffles Boulevard, Suntec City, Singapore 039593",
  // "Fuji Xerox Singapore, 80 Anson Road, Fuji Xerox Towers, S(079907)",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "ArtScience Museum",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "Hive@Sandcrawler, 1 Fusionopolis View #08-01, Singapore",
  // "Marina South Pier, 31 Marina Coastal Drive , Singapore",
  // "Sandcrawler, 1 Fusionopolis View #08-01 S138577, Singapore",
  // "HackerspaceSG",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "Penny Black, 27 Boat Quay, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Akamai Singapore office, 1 Raffles Place, #16-61, One Raffles Place Tower 2, Singapore 048616",
  // "IDA Labs Level 2 @ National Design Centre, 111 Middle Road, #02-04, Singapore 188969",
  // "Everything with Fries (Orchard Central), 181 Orchard Road, #01-24/25, Singapore",
  // "Thought Works,  Level 3, 87B Amoy Street, 069906, Singapore",
  // "NUS Enterprise@Blk71 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "Stuttgart Blackforest Boutique S-Café, 9 Bras Basah Road, #01-01 Rendezvous Hotel Gallery, Singapore",
  // "SR3, Town Plaza, UTown",
  // "川味人家 (Chuan Wei Ren Jia), 17 Mosque Street Singapore 059497 6220 5766",
  // "SR3, Town Plaza, University Town, National University of Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "Percolate, 136 Bedok North Ave 3, Singapore 460136",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "ArtScience Museum",
  // "SR3, Town Plaza, University Town",
  // "The Nest Theatre @ Innovation Centre",
  // "Heardable, Block 71, #01-17/18, 71 Ayer Rajah Crescent, Singapore",
  // "SR3, Town Plaza, University Town, National University of Singapore",
  // "ArtScience Museum",
  // "Science Centre Singapore",
  // "Google Singapore, Level 29, Asia Square Tower 1, 8 Marina View Singapore 018960, Singapore",
  // "Toa Payoh Public Library",
  // "IDA Lab @ National Design Center , #03-04 111 Middle Road, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Suntec City NUSS - The College Room, 3 Temasek Boulevard (Tower 5) #02- 401/402 Suntec City Mall Singapore 038983",
  // "Huge Singapore, 33 Ann Siang Rd, Suite 31A",
  // "Hive@Sandcrawler, 1 Fusionopolis View #08-01, Singapore",
  // "Raffles City Convention Centre, 80 Bras Basah Rd Singapore 189560",
  // "SR3, Town Plaza, University Town, National University of Singapore",
  // "The Nest Theatre @ Innovation Centre",
  // "Plug-In@Blk71",
  // "ArtScience Museum",
  // "ArtScience Museum",
  // "SR3, Town Plaza, University Town, National University of Singapore",
  // "Rhu Cross, Rhu Cross, Singapore",
  // "1 Fusionopolis Way, #05-10 Connexis North Tower, Singapore 138632",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "PayPal, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985, Singapore",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "ThoughtWorks, 87B Amoy Street #03/04, Singapore 069906",
  // "Neo Office, 53A Craig Road, Singapore",
  // "Hive@Sandcrawler, 1 Fusionopolis View #08-01, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "PayPal Singapore, Suntec Tower 5, 5 Temasek Boulevard #09-01 ",
  // "Five Tapas Bar, 25 Cuppage Road, Singapore",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Amazon Web Services Office, Level 10, 23 Church Street, Singapore",
  // "Oromo Coffee",
  // "SR3, Town Plaza, University Town",
  // "Paypal at Suntec , 5 Temasek Blvd, #07-01 Suntec Tower Five, Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "NTU Open Source Society",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "TH, Ayer Rajah Crescent, Singapore",
  // "SkyScanner Ltd, 39 Robinson Road #09-01 Robinson Point, Singapore",
  // "SR3, Town Plaza, University Town, National University of Singapore",
  // "HackerspaceSG",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "Suntec Convention Centre Level 4, Datwyler booth G04, Singapore",
  // "ThoughtWorks office, 87B Amoy Street, Level 3, Singapore",
  // "General Assembly Singapore, The Working Capitol, 1 Keong Saik Road, Level 3, Singapore 089101 (Turn left on the side lane beside Lollapalooza and walk up to level 3)",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "General Assembly Singapore, The Working Capitol, 1 Keong Saik Road, Level 3, Singapore 089101 (Turn left on the side lane beside Lollapalooza and walk up to",
  // "CATO, 237 south bridge road, Singapore",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "Akamai Singapore office, 1 Raffles Place, #16-61, One Raffles Place Tower 2, Singapore 048616",
  // "Kaplan Singapore, 1 Selegie Rd, 188306",
  // "Medical Alumni Association",
  // "SR3, Town Plaza (Level 2), University Town, NUS",
  // "TR +37 (Northspine)",
  // "Science Centre Singapore",
  // "HackerspaceSG",
  // "ArtScience Museum",
  // "IDA Labs @ NDC National Design Centre , 111 Middle Road, #03-04 Singapore 188969 ",
  // "Science Centre Singapore",
  // "Chin Chin Eating House, 19 Purvis St, Singapore 188598",
  // "NUS Hackerspace",
  // "5 Temasek Boulevard, Level 7, Suntec Tower 5, Singapore 038985",
  // "PayPal Singapore, Suntec Tower 5, 5 Temasek Boulevard #09-01 ",
  // "SPH Auditorium, 1000 Toa Payoh North, News Centre, Singapore 318994 ",
  // "大衆居酒屋２, 16 Enggor St. #01-14/15/16, Altez, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "ArtScience Museum",
  // "SR3, Town Plaza (Level 2), University Town, NUS",
  // "The Hub Singapore, 128 Prinsep Street, #01-01",
  // "Hall A, Science Centre Singapore",
  // "Science Centre Singapore, Einstein Room",
  // "Marina Bay Sands, Sands Expo and Convention Center, Cassia Ballroom (Level 3), 10 Bayfront Avenue, Singapore 01",
  // "Science Centre Singapore",
  // "General Assembly Singapore",
  // "Joe & Dough At Millenia Walk",
  // "Barclays, 10 Marina Boulevard, #23-01, Marina Bay Financial Centre Tower 2, Singapore",
  // "Hive@Sandcrawler, 1 Fusionopolis View #08-01, Singapore",
  // "AWS Offices Singapore, 23 Church Street, Capital Square #10-01, 049481 Singapore",
  // "Seminar Room 3, Town Plaza, University Town, National University of Singapore",
  // "Theatre @ the Nest, Innovation Centre",
  // "Toa Payoh Public Library",
  // "PayPal, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985, Singapore",
  // "Science Centre Singapore",
  // "ArtScience Museum",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "TradeGecko Office, 121 Telok Ayer, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "Delhi 6 Restaurant, #01-13 Republic Plaza 2, 9 Raffles Place, Singapore",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Red Hat, 8 Shenton Way, 10-01 AXA Tower, 068811 Singapore",
  // "Neo Innovation, 53A Craig Road, Singapore",
  // "AWS Offices Singapore, 23 Church Street, Capital Square, #10-01, Singapore - 049481, +65-67220300",
  // "Microsoft, Level 22 (Conf Room SINOMB 22CF-12), 1 Marina Boulevard, Singapore",
  // "HackerspaceSG",
  // "Cliftons Singapore , 108 Robinson Rd ",
  // "NTUC Auditorium, Level 7 NTUC Centre, One Marina Boulevard, Singapore",
  // "Neo Innovation , 53A Craig Road , 089691, Singapore",
  // "Netsuite, 9 Battery Road, #08-01, Straits Trading Building, Singapore",
  // "ArtScience Museum",
  // "TBA, TBA, Singapore",
  // "The Hub, 128 Prinsep Street, Singapore 188655",
  // "Ya Kun Kaya Toast, 18 China St #01-01, Singapore 049560",
  // "National Design Centre, 111 Middle Road, Singapore",
  // "Hackerspace.SG, 344B King George's Ave, King George's Building, Singapore",
  // "HackerspaceSG, 344 King George's Ave 208576, Singapore",
  // "Hive@Sandcrawler, 1 Fusionopolis View #08-01, Singapore",
  // "PayPal office in Suntec, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985 Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "Joe & Dough At Millenia Walk",
  // "HackerspaceSG",
  // "ST Innovation Lab - SPH, 1000 Toa Payoh North, Singapore",
  // "IDA Labs Level 3 @ National Design Centre, 111 Middle Road, #03-04, 188969, Singapore",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "SmartSpace, 261 Waterloo Street, #03-32, Singapore 180261",
  // "Microsoft Auditorium (Singapore), One Marina Boulevard, Level 21 Auditorium, Singapore 018989 ",
  // "Suntec City, 5 Temasek Blvd, #07-01 Suntec Tower Five, 038985",
  // "Annalakshmi Central Square, 20 Havelock Road, Singapore",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "Thoughtworks, 87B Amoy Street #04, Singapore 069906, Singapore",
  // "Digital Planetarium, Science Center Singapore, 21 Jurong Town Hall Road",
  // "Science Centre Singapore",
  // "CATO, 237 south bridge road, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "The Pavilion @ Far East Square",
  // "Akamai Singapore office, 1 Raffles Place, #16-61, One Raffles Place Tower 2, Singapore 048616",
  // "Medical Alumni Association",
  // "Hotel Meritus Mandarin Orchard, 333 Orchard Road, Singapore 238867",
  // "PayPal office, 5 Temasek Blvd, Suntec Tower Five, Level 7, Singapore",
  // "Microsoft Singapore, One Marina Boulevard, Level 22, Meeting Room",
  // "IDA Labs @ NDC National Design Centre , 111 Middle Road, #03-04 Singapore 188969 ",
  // "Science Centre Singapore",
  // "Paypal at Suntec , 5 Temasek Blvd, #07-01 Suntec Tower Five, Nearest Mrt:Promenade(Yellow Line), Singapore",
  // "HackerspaceSG",
  // "Suntec Convention & Exhibition Center, #1 Raffles Blvd, Singapore",
  // "Microsoft Singpaore, One Marina Boulevard, Level 21 Auditorum, Singapore 018989",
  // "Tim & Wei's Residence, 244A Tanjong Katong Road, Singapore",
  // "NUS Enterprise@Blk71, 71 Ayer Rajah Crescent, #02-01, Singapore 139951",
  // "Suntec Convention Center, Suntec Convention Center, Singapore"
];

describe('Graph for Events per Location', function() {
  describe('#hasSimilarLocation', function() {
    it('returns new', function() {
      var location = 'Suntec';
      var reply = eventPerLocationLib.hasSimilarLocation(location, [])

      expect(reply.length).to.equal(1);
      expect(reply[ 0 ].complete).to.equal(location);
      expect(reply[ 0 ].all[ 0 ]).to.equal(location);
    })

    it('returns with the new location', function() {
      var location = 'Suntec Tower Microsoft';
      var locationList = [
        {
          complete: 'Suntec Tower 5',
          all: [ 'Suntec Tower 5' ]
        }
      ];
      var reply = eventPerLocationLib.hasSimilarLocation(location, locationList);

      expect(reply.length).to.equal(1);
      expect(reply[ 0 ].complete).to.equal(location);
      expect(reply[ 0 ].all.length).to.equal(2);
    })
  })

  it.only('returns locationList', function() {
    var locationList = [];

    locations.forEach(function(eachLocation) {
      locationList = eventPerLocationLib.hasSimilarLocation(eachLocation, locationList);
    })

    console.log(locationList)
    console.log(locationList.length)
  })
})
